"""短线交易信号阈值（实盘两周后再校准）。"""

# 竞价保量：竞价量 / 昨全天量
KEEP_VOL_ZT = 0.03
KEEP_VOL_WATCH = 0.02
KEEP_AMOUNT = 20_000_000  # 竞价额（元）并列条件
SHRINK_DIVERGE = 0.015    # 高开但低于此视为缩量分歧

# 盘中极致缩量 / 高位放量（时间修正量比）
SHRINK_EXTREME = 0.40
HIGH_VOL_RATIO = 2.0
HIGH_NEAR = 0.03          # 现价在 20 日高 3% 内
RET5_HIGH = 0.15
LIANBAN_HIGH = 2

# 板块集体 / 偏离
COLLECTIVE_MIN = 3
COLLECTIVE_SHARE = 0.60
COLLECTIVE_VR = 1.8
OUTLIER_PCT = 4.0
OUTLIER_PCT_20CM = 6.0

# 空间
LADDER_OPEN_STRONG = 0.80
LADDER_OPEN_WEAK = 0.40
BREADTH_SHIFT = 0.30      # 涨停家数相对 3 日均
ZHABAN_HOT = 0.40

SKIP_BEFORE = (9, 35)
DISPLAY_LIMIT = 8              # 一期默认，兼容
DISPLAY_B1_WATCH = 12
DISPLAY_B1_DISCOVERY_ACTION = 5
DISPLAY_A7 = 12
DISPLAY_A3 = 12
DISPLAY_WIDE = 30              # a0 / a4 / 仪表盘

DISCOVERY_STOCK_CAP = 80
RS_INDUSTRY_TOP = 8
RS_CORE_PER_INDUSTRY = 3
LHB_DISCOVERY_CAP = 30
BOARD_TOP_N = 10

AUCTION_YOY = 0.80             # 今竞价量/昨竞价量
BOARD_HIGH_OPEN_PCT = 3.0      # 百分点
BOARD_LOW_OPEN_PCT = -3.0
FLOW_SPIKE = 2.0
RS_LEADER_RANK = 8
RS_LEADER_UP = 3               # 排名上升至少 N 名（rank 变小）
ROTATION_LEAD_RANK = 15
QUAD_RS_ZERO = 0.0
QUAD_CROWDING = 0.8            # 与仪表盘 hline 一致
QUAD_HUNT_LIMIT = 8
QUAD_CHASE_LIMIT = 8
QUAD_WATCH_LIMIT = 6
PATH_DAYS = 5
